select * from employee;

SELECT COUNT(DNO) FROM EMPLOYEE;
SELECT DISTINCT DNO AS "활동 부서수" FROM EMPLOYEE;
SELECT COUNT(DISTINCT DNO) AS "활동 부서수" FROM EMPLOYEE;
SELECT COUNT(DISTINCT DNO) AS "활동 부서수" FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT COUNT(COMMISSION) FROM EMPLOYEE;

SELECT COUNT(*) FROM EMPLOYEE;

SELECT ENAME, SUM(SALARY) FROM EMPLOYEE;

SELECT DNO, SUM(SALARY) FROM EMPLOYEE GROUP BY (DNO);





SELECT MAX(SALARY) AS "Maximum", MIN(SALARY) AS "Minimum", SUM(SALARY) AS "Sum",ROUND(AVG(SALARY)) AS "Average" FROM EMPLOYEE;
SELECT JOB,MAX(SALARY) AS "Maximum", MIN(SALARY) AS "Minimum", SUM(SALARY) AS "Sum",ROUND(AVG(SALARY)) AS "Average" FROM EMPLOYEE GROUP BY JOB;
SELECT JOB, COUNT(*) FROM EMPLOYEE GROUP BY JOB;
SELECT COUNT(MANAGER) FROM EMPLOYEE;
SELECT (MAX(SALARY)-MIN(SALARY)) AS DIFFERNCE FROM EMPLOYEE;
SELECT JOB, MIN(SALARY) FROM EMPLOYEE GROUP BY JOB HAVING MIN(SALARY) >= 2000 ORDER BY MIN(SALARY) DESC ;
SELECT DNO, COUNT(DNO) AS "Number of People",  ROUND(AVG(SALARY),2)AS "Salary" FROM EMPLOYEE GROUP BY DNO ORDER BY AVG(SALARY) DESC;
SELECT DECODE(DNO,10,'SALES',20,'RESEARCH',30,'ACCOUNTING') AS "Location", DECODE(DNO,10,'CHICAGO',20,'DALLAS',30,'NEW YORK') AS "Location", COUNT(DNO) AS "Number of People", ROUND(AVG(SALARY)) AS "Salary" FROM EMPLOYEE GROUP BY DNO;
SELECT JOB, DECODE(DNO,10,SUM(SALARY)) AS "부서 10", DECODE(DNO,20,SUM(SALARY)) AS "부서 20", DECODE(DNO,30,SUM(SALARY)) AS "부서 30",DNO,SUM(SALARY) AS "총액" FROM EMPLOYEE  GROUP BY JOB, DNO ORDER BY DNO, JOB;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;

SELECT ENAME, SALARY FROM EMPLOYEE E,DEPARTMENT D WHERE E.DNO=D.DNO AND D.LOC='NEW YORK';
SELECT ENAME, SALARY FROM EMPLOYEE E natural join DEPARTMENT D WHERE D.LOC='NEW YORK';
SELECT ENAME, SALARY FROM EMPLOYEE E JOIN DEPARTMENT D USING(DNO) WHERE D.LOC='NEW YORK';

SELECT ENAME, HIREDATE FROM EMPLOYEE E, DEPARTMENT D WHERE E.DNO=D.DNO AND D.DNAME='ACCOUNTING';
SELECT ENAME, HIREDATE FROM EMPLOYEE E natural join DEPARTMENT D WHERE D.DNAME='ACCOUNTING';
SELECT ENAME, HIREDATE FROM EMPLOYEE E JOIN DEPARTMENT D USING(DNO) WHERE D.DNAME='ACCOUNTING';

SELECT ENAME, D.DNAME FROM EMPLOYEE E, DEPARTMENT D WHERE E.DNO=D.DNO AND E.JOB='MANAGER';
SELECT ENAME, D.DNAME FROM EMPLOYEE E natural join DEPARTMENT D WHERE E.JOB='MANAGER';
SELECT ENAME, D.DNAME FROM EMPLOYEE E JOIN DEPARTMENT D USING(DNO) WHERE E.JOB='MANAGER';

SELECT * FROM SALGRADE;
SELECT ENAME, SALARY, GRADE FROM EMPLOYEE, SALGRADE WHERE SALARY>=LOSAL AND SALARY<HISAL;

SELECT ENAME, SALARY, DNAME, GRADE FROM EMPLOYEE,DEPARTMENT,SALGRADE WHERE (EMPLOYEE.DNO=DEPARTMENT.DNO) AND (SALARY BETWEEN LOSAL AND HISAL);

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM SALGRADE;

SELECT E.ENAME, E.DNO, D.DNAME FROM EMPLOYEE E,DEPARTMENT D WHERE E.DNO=D.DNO AND E.ENAME='SCOTT';
SELECT ENAME,DNAME,LOC FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DNO=D.DNO ORDER BY LOC DESC;
SELECT DNO, E.JOB, D.LOC  FROM EMPLOYEE E JOIN DEPARTMENT D USING(DNO) WHERE DNO=10;
SELECT ENAME, DNAME,LOC FROM EMPLOYEE E NATURAL JOIN DEPARTMENT WHERE COMMISSION IS NOT NULL AND COMMISSION!=0;
SELECT ENAME, DNAME FROM EMPLOYEE E NATURAL JOIN DEPARTMENT D WHERE ENAME LIKE '%A%';
SELECT ENAME, JOB, DNO, DNAME FROM EMPLOYEE E NATURAL JOIN DEPARTMENT D WHERE LOC='NEW YORK';
SELECT E1.ENAME AS "Employee", E1.ENO AS "Emp#", E2.ENO AS "Manger",  E2.ENAME FROM EMPLOYEE E1, EMPLOYEE E2 WHERE E1.MANAGER=E2.ENO;
SELECT E1.ENAME AS "Employee", E1.ENO AS "Emp#", E2.ENO AS "Manger",  E2.ENAME FROM EMPLOYEE E1, EMPLOYEE E2 WHERE E1.MANAGER=E2.ENO(+);
SELECT E1.ENAME AS "이름", E1.DNO AS "부서번호", E2.ENAME AS "동료" FROM EMPLOYEE E1, EMPLOYEE E2 WHERE E1.ENAME='SCOTT' AND E1.DNO=E2.DNO AND E2.ENAME!='SCOTT';
SELECT E2.ENAME AS "ENAME", E2.HIREDATE AS "HIREDATE" FROM EMPLOYEE E1, EMPLOYEE E2 WHERE E1.ENAME='WARD' AND E1.HIREDATE<E2.HIREDATE;
SELECT E1.ENAME AS "ENAME", E1.HIREDATE AS "HIREDATE", E2.ENAME AS "ENAME",  E2.HIREDATE AS "HIREDATE" FROM EMPLOYEE E1, EMPLOYEE E2 WHERE E1.MANAGER=E2.ENO AND E1.HIREDATE<=E2.HIREDATE ;

SELECT NVL(COMMISSION,'X') FROM EMPLOYEE WHERE 1=2;

SELECT E.ENAME, E.DNO, D.DNAME FROM EMPLOYEE E,DEPARTMENT D WHERE E.DNO=:D.DNO;
























































