SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT  * FROM  EMPLOYEE WHERE DNO=(SELECT DNO FROM EMPLOYEE WHERE ENAME='SCOTT');
SELECT ENAME,JOB,SALARY FROM EMPLOYEE WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEE);
SELECT ENAME FROM EMPLOYEE WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEE);
SELECT DNO, AVG(SALARY) FROM EMPLOYEE GROUP BY DNO HAVING AVG(SALARY)>(SELECT AVG(SALARY) FROM EMPLOYEE WHERE DNO=30);

SELECT ENO, ENAME, DNO FROM EMPLOYEE WHERE DNO IN(SELECT DNO FROM DEPARTMENT WHERE DNO>10);
SELECT * FROM EMPLOYEE WHERE SALARY > ANY(SELECT AVG(SALARY) FROM EMPLOYEE GROUP BY DNO);
SELECT * FROM EMPLOYEE WHERE SALARY > ALL(SELECT AVG(SALARY) FROM EMPLOYEE GROUP BY DNO);

SELECT ROWNUM, ENO,ENAME, SALARY FROM EMPLOYEE ORDER BY SALARY DESC;

SELECT ENAME, JOB FROM EMPLOYEE WHERE JOB=(SELECT JOB FROM EMPLOYEE WHERE ENO=7788);
SELECT ENAME, JOB FROM EMPLOYEE WHERE SALARY>(SELECT SALARY FROM EMPLOYEE WHERE ENO=7499);
SELECT ENAME, JOB, SALARY FROM EMPLOYEE WHERE SALARY=(SELECT MIN(SALARY) FROM EMPLOYEE);
SELECT JOB, ROUND(AVG(SALARY),1) FROM EMPLOYEE GROUP BY JOB HAVING (SELECT ROWNUN,JOB, ROUND(AVG(SALARY),1) FROM EMPLOYEE GROUP BY JOB HAVING ROWNUM<=1);
SELECT ENAME,SALARY,DNO FROM EMPLOYEE WHERE SALARY IN(SELECT  MIN(SALARY) FROM EMPLOYEE GROUP BY DNO);
SELECT ENO,ENAME,JOB,SALARY FROM EMPLOYEE WHERE SALARY<ALL(SELECT SALARY FROM EMPLOYEE WHERE JOB='ANALYST');
SELECT ENAME FROM EMPLOYEE WHERE MANAGER IS NULL;
SELECT ENAME FROM EMPLOYEE WHERE MANAGER IS NOT NULL;
SELECT ENAME,HIREDATE FROM EMPLOYEE WHERE DNO=(SELECT DNO FROM EMPLOYEE WHERE ENAME='BLAKE') AND ENAME!='BLAKE';
SELECT ENO, ENAME FROM EMPLOYEE WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEE) ORDER BY SALARY;
SELECT ENO, ENAME FROM EMPLOYEE WHERE ENO = ANY(SELECT  ENO FROM EMPLOYEE WHERE LIKE('%K%'));

CREATE VIEW EMP_SALES AS SELECT * FROM EMPLOYEE WHERE SALARY>2000;
SELECT * FROM EMP_SALES;

CREATE OR REPLACE VIEW EMP_SALARY_VIEW AS SELECT DNO AS "부서번호", SUM(SALARY) AS "급여 합", AVG(SALARY) AS "급여평균" FROM EMPLOYEE GROUP BY DNO;
SELECT * FROM EMP_SALARY_VIEW WHERE "부서번호"=10;

CREATE TABLE BOOK(
            BOOK_NUM NUMBER PRIMARY KEY,
            TITLE VARCHAR2(50),
            PUBLISHER VARCHAR2(50),
            PRICE NUMBER
);
CREATE SEQUENCE BOOK_SEQ
    START WITH 50
    INCREMENT BY 2;

SELECT BOOK_SEQ.CURRVAL FROM DUAL; 에러남
SELECT BOOK_SEQ.NEXTVAL FROM DUAL;

INSERT INTO BOOK(BOOK_NUM, TITLE, PUBLISHER, PRICE) VALUES(BOOK_SEQ.NEXTVAL, '자바의 정석','SDS',20000);
 
 SELECT * FROM BOOK;    











